<h1 style="color:purple;"> <strong> <center> Taller Numpy - Inteligencia Artificial</center></strong></h1>

<h3 style="color:black;"><center><strong>Nataly Ramírez Urrego (naramirezur@unal.edu.co)</strong></center></h3>

Tomado de: <https://github.com/AprendizajeProfundo/Diplomado/blob/master/Temas/M%C3%B3dulo%2013-%20Talleres/Cuadernos/Taller_Pandas.ipynb>

Autores: 

1. Oleg Jarma, ojarmam@unal.edu.co
2. Julieth López, julalopezcas@unal.edu.co

## Importación de la librería **Numpy**

In [4]:
import numpy as np

## Utilidades de Numpy

Numpy es un paquete de python dedicado principalmente al manejo de conjuntos o "arrays". Extendiendose luego al álgebra lineal, matrices y probabilidad. Usar arrays es más rápido y consume menos memoria. Algo altamente necesario cuando se hacen operaciones de gran tamaño como puede ser el algebra matricial.


## Creación de arrays


Para la creación de arrays es posible utilizar números, listas o tuplas.

Antes de crear estos arreglos, definamos qué son las tuplas y las listas.

* **Tuplas (tuple):** Esta es una colección de objetos que están ordenados y son inmutables (no pueden modificarse). Las tuplas admiten elementos repetidos y sus miembros son indexados. Las tuplas se crean y se reconocen porque los elementos se escriben entre paréntesis circulares: '()'.

* **Listas (list):** Son colecciones de objetos que están ordenado y son mutables, es decir, sus contenidos pueden ser modificados. Los elementos son indexados y permite duplicados. Las listas se distingen porque sus elementos están encerrados entre paréntesis cuadrados '[ ]'.

#### Array de dimensión 0

In [17]:
a=np.array(19) #array de dimensión 0
print("a =",a,"\n")
print(a.ndim) #Imprime la dimensión del arreglo

a = 19 

0


#### Array de dimensión 1

In [18]:
b=np.array([1,2,3,4]) #array de dimensión 1
print("b =",b,"\n")
print(b.ndim)#Imprime la dimensión del arreglo

b = [1 2 3 4] 

1


#### Array de dimensión 2

In [19]:
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
print("c =",c,"\n")
print(c.ndim) #Imprime la dimensión del arreglo

c = [[1 2 3 4]
 [5 6 7 8]] 

2


#### Array de dimensión 3

In [20]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3
print("d =",d,"\n")
print(d.ndim) #Imprime la dimensión del arreglo

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

3


## Indexación básica

El proceso de indexación en numpy es similar al de las listas en python. Cada número implica buscar la posición en cada dimensión del array.

La primera posición comienza en el número 0, es decir que la posición 0 es el primer elemento del objeto que tenemos.

In [21]:
print("a =",a,"\n")
print("a =",a)

a = 19 

a = 19


Note que **a** es un objeto con un único elemento así que solo basta con llamarlo.

In [22]:
print("b =",b,"\n")
print("b[2] = ",b[2])

b = [1 2 3 4] 

b[2] =  3


Para los elementos del objeto **b**, se tiene que la posición 2 sería el elemento 3.

In [23]:
print("c =",c,"\n")
print("c[1] =",c[1])

c = [[1 2 3 4]
 [5 6 7 8]] 

c[1] = [5 6 7 8]


Para el elementeo **c**, el conjunto de elementos que corresponde a la posición 1 es [5 6 7 8]. 

In [24]:
print("d =",d,"\n")
print("d[1] =",d[1])

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


En cuanto al elemento **d** se tiene que el elemento que corresponde a la posición 1 es  [[ 9 10 11 12]
  [13 14 15 16]]]. 

In [28]:
print("c =",c,"\n")
print("c[1,2] =",c[1,2])

c = [[1 2 3 4]
 [5 6 7 8]] 

c[1,2] = 7


Para el anterior código se entiende que se llama al elemento en la posición 3 de la columna 2 del objeto **c**.

In [29]:
print("d =",d,"\n")
print("d[1,0,2] =",d[1,0,2])

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d[1,0,2] = 11


En el anterior ejemplo, tenemos un arreglo de dos matrices 2x4. La posición [1, 0, 2] indica la segunda matriz, posteriormente la primera columna, y de esta columna el tercer objeto. 

In [30]:
print(b[1:4]) #b = [1 2 3 4] 

[2 3 4]


Por otro lado, también se puede indicar los elementos que se quieren el objeto.

In [31]:
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[6 7]


Para este caso, se tiene la segunda columna de c y los últimos 3 objetos.

## Diferentes tipos de datos en los arrays

Los arrays no están limitados a números enteros, pueden también tener cadenas, booleanos, o de punto flotante.

In [32]:
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)

<U7


Podemos manipular el tipo de los datos del array dentro de la función de creación del array np.array, siempre y cuando el cambio sea posible. Por ejemplo podemos pasar enteros a cadenas (integers a strings) pero no viceversa.

In [33]:
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


## Forma de los arrays

La forma de los arrays es distinta a la dimensión. Esta se define como el número de elementos de la dimensión.

In [34]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


Como **a** es de dimensión 0, aparece vacío.

Para **b**, con una dimensión, hay 4 elementos.

**c**, con dimensión 2 tiene 4 elementos por dimensión. 

Por último, **d** es de dimensión 3, hay dos objetos en d, los cuales tienen también otros dos objetos los cuales tienen 4 elementos.

### Reformar arrays
Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión.

In [35]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [36]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### Dimensión desconocida

Podemos definir el cambio de forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de definir el tamaño que mejor se ajuste.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Transpuesta

Para transponer el array utilizamos `.T`

In [39]:
print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Iterar arrays

Podemos usar los métodos tradicionales para iterar.

In [41]:
for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


Si queremos iterar cada elemento, necesitamos un for por cada dimensión

In [42]:
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


Esto por supuesto no es óptimo. Así que numpy tiene la función `nditer()` para estos casos.

In [43]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


## Aplicar operaciones entre arrays

### Suma

numpy tiene dos funciones, `np.add()` y `np.sum()`. El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [44]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [45]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


Si aplicamos un eje en `np.sum()`, se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtienen los mismos resultados que `np.add()`

In [46]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [47]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

### Multiplicación

El primer caso de multiplicación es `np.prod()`, que funciona similar que `np.sum()`.

In [48]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


### Multiplicación Matricial

Para la multiplicación de matrices usamos `np.matmul()` o `np.dot()`. hay que tener en cuenta la forma de las matrices

In [49]:
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan distinto con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [51]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [52]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con *matmul* no se pueden multiplicar escalares **c.A** (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con dot, donde este toma los números dentro de las matrices como elementos.

In [53]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])